/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package kütüphanem;

import Yardım.Yardım;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author İLKER
 */
public class Kütüphanem extends javax.swing.JFrame {

    DefaultTableModel model;
    public Kütüphanem() throws SQLException {
        initComponents();
        
        populateTable();
    }
    public void populateTable() throws SQLException{//tabloDoldur metodumuz
        model=(DefaultTableModel) tblKitaplar.getModel();
        model.setRowCount(0);//iki defa işlem yapmaması için tabloyu bir defa temizliyoruz.
        ArrayList<Kitap> kitaplar = getKitaplar();
        for (Kitap kitap : kitaplar) {
            Object[] row = {kitap.getKitapAdı(), kitap.getYayıneviAdı(), kitap.getYazarAdı(), kitap.getKitapDili(), kitap.getSayfaSayısı(),kitap.getYayınYılı()};
            model.addRow(row);
        }
        
    }
    public ArrayList<Kitap> getKitaplar() throws SQLException {
        Connection connection = null;
        DbHelper dbHelper = new DbHelper();
        Statement statement = null;
        ResultSet resultSet;
        ArrayList<Kitap> kitaplar = null;

        try {
            connection = dbHelper.getConnection();
            statement = connection.createStatement();
            resultSet = statement.executeQuery("select * from kitap");
            kitaplar = new ArrayList<Kitap>();
            while (resultSet.next()) {
                kitaplar.add(new Kitap(
                        resultSet.getInt("Sayfa Sayısı"),
                        resultSet.getString("Yazar Adı"),
                        resultSet.getString("Yayınevi Adı"),
                        resultSet.getString("Kitap Dili"),
                        resultSet.getString("Kitap Adı"),
                        resultSet.getInt("Yayın Yılı")
                        
                ));
            }

        } catch (SQLException exception) {
            dbHelper.showErrorMessage(exception);
        } finally {
            statement.close();
            connection.close();
        }
        return kitaplar;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabelExit = new javax.swing.JLabel();
        jLabelMinimize = new javax.swing.JLabel();
        jButtonKitapEkle = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jButtonYardım = new javax.swing.JButton();
        jButtonAyarlar = new javax.swing.JButton();
        jButtonSırala = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblKitaplar = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        txtSearch = new javax.swing.JTextField();
        lblKitapAdı = new javax.swing.JLabel();
        lblYazarAdı = new javax.swing.JLabel();
        lblYayıneviAdı = new javax.swing.JLabel();
        lblKitapDili = new javax.swing.JLabel();
        lblSayfaSayısı = new javax.swing.JLabel();
        lblYayınDili = new javax.swing.JLabel();
        txtKitapAdı = new javax.swing.JTextField();
        txtYayıneviAdı = new javax.swing.JTextField();
        txtYazarAdı = new javax.swing.JTextField();
        txtKitapDili = new javax.swing.JTextField();
        txtSayfaSayısı = new javax.swing.JTextField();
        txtYayınYılı = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(60, 166, 140));
        jPanel1.setForeground(new java.awt.Color(187, 20, 17));

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel1.setText("KİTAPLIĞIM");

        jLabelExit.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabelExit.setText("X");
        jLabelExit.setAutoscrolls(true);
        jLabelExit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelExit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelExitMouseClicked(evt);
            }
        });

        jLabelMinimize.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabelMinimize.setText("-");
        jLabelMinimize.setAutoscrolls(true);
        jLabelMinimize.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelMinimize.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelMinimizeMouseClicked(evt);
            }
        });

        jButtonKitapEkle.setBackground(new java.awt.Color(60, 141, 224));
        jButtonKitapEkle.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jButtonKitapEkle.setForeground(new java.awt.Color(0, 0, 0));
        jButtonKitapEkle.setText("Kitap Ekle");
        jButtonKitapEkle.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonKitapEkle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonKitapEkleActionPerformed(evt);
            }
        });

        jSeparator1.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));

        jButtonYardım.setBackground(new java.awt.Color(60, 141, 224));
        jButtonYardım.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jButtonYardım.setForeground(new java.awt.Color(0, 0, 0));
        jButtonYardım.setText("Yardım");
        jButtonYardım.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonYardım.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonYardımActionPerformed(evt);
            }
        });

        jButtonAyarlar.setBackground(new java.awt.Color(60, 141, 224));
        jButtonAyarlar.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jButtonAyarlar.setForeground(new java.awt.Color(0, 0, 0));
        jButtonAyarlar.setText("Ayarlar");
        jButtonAyarlar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonAyarlar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAyarlarActionPerformed(evt);
            }
        });

        jButtonSırala.setBackground(new java.awt.Color(60, 141, 224));
        jButtonSırala.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jButtonSırala.setForeground(new java.awt.Color(0, 0, 0));
        jButtonSırala.setText("Sırala");
        jButtonSırala.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonSırala.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSıralaActionPerformed(evt);
            }
        });

        tblKitaplar.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Yayınevi Adı", "Yazar Adı", "Kitap Dİli", "Kitap Adı", "Sayfa Sayısı", "Yayın Yılı"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblKitaplar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tblKitaplarMousePressed(evt);
            }
        });
        jScrollPane2.setViewportView(tblKitaplar);
        if (tblKitaplar.getColumnModel().getColumnCount() > 0) {
            tblKitaplar.getColumnModel().getColumn(0).setResizable(false);
            tblKitaplar.getColumnModel().getColumn(1).setResizable(false);
            tblKitaplar.getColumnModel().getColumn(2).setResizable(false);
            tblKitaplar.getColumnModel().getColumn(3).setResizable(false);
            tblKitaplar.getColumnModel().getColumn(4).setResizable(false);
            tblKitaplar.getColumnModel().getColumn(5).setResizable(false);
        }

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Kitap Ara:");

        txtSearch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtSearchKeyReleased(evt);
            }
        });

        lblKitapAdı.setFont(new java.awt.Font("Dialog", 2, 14)); // NOI18N
        lblKitapAdı.setForeground(new java.awt.Color(0, 0, 0));
        lblKitapAdı.setText("Kitap Adı:");

        lblYazarAdı.setFont(new java.awt.Font("Dialog", 2, 14)); // NOI18N
        lblYazarAdı.setForeground(new java.awt.Color(0, 0, 0));
        lblYazarAdı.setText("Yazar Adı:");

        lblYayıneviAdı.setFont(new java.awt.Font("Dialog", 2, 14)); // NOI18N
        lblYayıneviAdı.setForeground(new java.awt.Color(0, 0, 0));
        lblYayıneviAdı.setText("Yayınevi Adı:");

        lblKitapDili.setFont(new java.awt.Font("Dialog", 2, 14)); // NOI18N
        lblKitapDili.setForeground(new java.awt.Color(0, 0, 0));
        lblKitapDili.setText("Kitap Diliı:");

        lblSayfaSayısı.setFont(new java.awt.Font("Dialog", 2, 14)); // NOI18N
        lblSayfaSayısı.setForeground(new java.awt.Color(0, 0, 0));
        lblSayfaSayısı.setText("Sayfa Sayısı:");

        lblYayınDili.setFont(new java.awt.Font("Dialog", 2, 14)); // NOI18N
        lblYayınDili.setForeground(new java.awt.Color(0, 0, 0));
        lblYayınDili.setText("Yayın Yılı:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabelMinimize)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabelExit))
                    .addComponent(jSeparator1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addComponent(jButtonKitapEkle)
                                        .addGap(80, 80, 80)))
                                .addComponent(jButtonAyarlar))
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 763, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(lblKitapAdı)
                                        .addGap(33, 33, 33)
                                        .addComponent(txtKitapAdı, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lblYayıneviAdı)
                                            .addComponent(lblYazarAdı))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtYayıneviAdı)
                                            .addComponent(txtYazarAdı))))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(lblKitapDili)
                                        .addGap(26, 26, 26)
                                        .addComponent(txtKitapDili, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lblSayfaSayısı)
                                            .addComponent(lblYayınDili))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtSayfaSayısı)
                                            .addComponent(txtYayınYılı))))
                                .addGap(16, 16, 16)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(63, 63, 63)
                                        .addComponent(jButtonYardım))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(64, 64, 64)
                                        .addComponent(jButtonSırala, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                        .addContainerGap())))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabelExit)
                    .addComponent(jLabelMinimize))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(txtKitapDili, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(90, 90, 90))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblKitapAdı)
                                    .addComponent(txtKitapAdı, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblKitapDili))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblYayıneviAdı)
                                    .addComponent(txtYayıneviAdı, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblSayfaSayısı)
                                    .addComponent(txtSayfaSayısı, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblYazarAdı)
                                    .addComponent(txtYazarAdı, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblYayınDili)
                                    .addComponent(txtYayınYılı, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)))
                        .addComponent(jButtonKitapEkle))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButtonYardım)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                        .addComponent(jButtonSırala)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 47, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonAyarlar)
                    .addComponent(jLabel2)
                    .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonAyarlarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAyarlarActionPerformed
        Ayarlar ayarlar=new Ayarlar();
        ayarlar.setVisible(true);
        ayarlar.pack();
        ayarlar.setLocationRelativeTo(null);
        ayarlar.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_jButtonAyarlarActionPerformed

    private void jButtonYardımActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonYardımActionPerformed
        Yardım yardım=new Yardım();
        yardım.setVisible(true);
        yardım.pack();
        yardım.setLocationRelativeTo(null);
        yardım.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_jButtonYardımActionPerformed

    private void jButtonKitapEkleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonKitapEkleActionPerformed

        Connection connection=null;
        DbHelper dbHelper=new DbHelper();
        PreparedStatement statement=null;
        try {
            connection = dbHelper.getConnection();
            String sql = "insert into kitap (Kitap Adı,Yayınevi Adı,Yazar Adı,Kitap Dili, Sayfa Sayısı, Yayın Yılı) values(?,?,?,?,?,?)";
            statement = connection.prepareStatement(sql);
            statement.setString(4, txtKitapAdı.getText());
            statement.setString(1, txtYayıneviAdı.getText());
            statement.setString(2, txtYazarAdı.getText());
            statement.setString(3, txtKitapDili.getText());
            statement.setInt(5,Integer.valueOf(txtSayfaSayısı.getText()));
            statement.setInt(6,Integer.valueOf(txtYayınYılı.getText()));
            int result = statement.executeUpdate();

            populateTable();//tablo doldur

        } catch (SQLException exception) {
            dbHelper.showErrorMessage(exception);
        } finally {
            try {
                statement.close();
                connection.close();
            } catch (SQLException ex) {

            }

            }
    }//GEN-LAST:event_jButtonKitapEkleActionPerformed

    private void jLabelMinimizeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelMinimizeMouseClicked

        this.setState(JFrame.ICONIFIED);//pnecerenin küçültülmesini sağlar.
    }//GEN-LAST:event_jLabelMinimizeMouseClicked

    private void jLabelExitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelExitMouseClicked

        System.exit(0);//fare ile tıklayınca pencereyi kapatmayı sağlar
    }//GEN-LAST:event_jLabelExitMouseClicked

    private void txtSearchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSearchKeyReleased

        String searchKey=txtSearch.getText();
        TableRowSorter<DefaultTableModel> tableRowSorter=new TableRowSorter<DefaultTableModel>(model);
        tblKitaplar.setRowSorter(tableRowSorter);
        tableRowSorter.setRowFilter(RowFilter.regexFilter(searchKey));
    }//GEN-LAST:event_txtSearchKeyReleased

    private void jButtonSıralaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSıralaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonSıralaActionPerformed

    private void tblKitaplarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblKitaplarMousePressed
        txtKitapAdı.setText(tblKitaplar.getValueAt(tblKitaplar.getSelectedRow(), 3).toString());
        txtYayıneviAdı.setText(tblKitaplar.getValueAt(tblKitaplar.getSelectedRow(), 0).toString());
        txtYazarAdı.setText(tblKitaplar.getValueAt(tblKitaplar.getSelectedRow(), 1).toString());
        txtKitapDili.setText(tblKitaplar.getValueAt(tblKitaplar.getSelectedRow(), 2).toString());
        txtSayfaSayısı.setText(tblKitaplar.getValueAt(tblKitaplar.getSelectedRow(), 4).toString());
        txtYayınYılı.setText(tblKitaplar.getValueAt(tblKitaplar.getSelectedRow(), 5).toString());
    }//GEN-LAST:event_tblKitaplarMousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Kütüphanem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Kütüphanem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Kütüphanem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Kütüphanem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new Kütüphanem().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(Kütüphanem.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAyarlar;
    private javax.swing.JButton jButtonKitapEkle;
    private javax.swing.JButton jButtonSırala;
    private javax.swing.JButton jButtonYardım;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabelExit;
    private javax.swing.JLabel jLabelMinimize;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblKitapAdı;
    private javax.swing.JLabel lblKitapDili;
    private javax.swing.JLabel lblSayfaSayısı;
    private javax.swing.JLabel lblYayınDili;
    private javax.swing.JLabel lblYayıneviAdı;
    private javax.swing.JLabel lblYazarAdı;
    private javax.swing.JTable tblKitaplar;
    private javax.swing.JTextField txtKitapAdı;
    private javax.swing.JTextField txtKitapDili;
    private javax.swing.JTextField txtSayfaSayısı;
    private javax.swing.JTextField txtSearch;
    private javax.swing.JTextField txtYayınYılı;
    private javax.swing.JTextField txtYayıneviAdı;
    private javax.swing.JTextField txtYazarAdı;
    // End of variables declaration//GEN-END:variables
}
